### PR TITLE
Change links & code owners

### PR DESCRIPTION
**Pull request by huayunh**
#### Changes proposed in this Pull Request:
- Update all links to point to our GitHub enterprise org
- Remove Evan & update code owner user names

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
Is this the plan for changing all closed issues and updating all the links?

**Comment by huayunh** [comment]
@JeffGreiner-eaton, What do you mean by "changing all closed issues"?

**Comment by JeffGreiner-eaton** [comment]
> @JeffGreiner-eaton, What do you mean by "changing all closed issues"?

what you did in this PR. Pointing all the closed issues that are in the change log to GHE...
([#530](https://github.com/brightlayer-ui/angular-component-library/issues/530))
to
([#530](https://github.com/etn-ccis/blui-angular-component-library/issues/530))

**Review by JeffGreiner-eaton — APPROVED** [review]

**Review by EvanMcLaughlin-eaton — APPROVED** [review]
Looks good to me; @huayunh I think you're going to need to re-login to circleci to get this workflow to run in CI (even though it will pass).

**Comment by huayunh** [comment]
I did it yesterday after I eventually understood what CI is telling me

**Comment by EvanMcLaughlin-eaton** [comment]
Hmmm, still not luck.  I cannot re-run the pipeline myself, the option to do that is disabled for me.  After you re-auth, are you able to see this pipeline running?

**Review by daileytj — APPROVED** [review]

**Pull request merged**
