### PR TITLE
build issue fixed

### PR DESCRIPTION
**Pull request by RaghavendranC-Eaton**
Fixes # build issue fixed.

#### Changes proposed in this Pull Request:
-  Added include path to fix the build process. now the build lib working fine.
- 
- 

#### Screenshots / Screen Recording (if applicable)
-

#### To Test:
-  yarn test

#### Any specific feedback you are looking for?
-

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
can you explain the which build and the error?

**Comment by RaghavendranC-Eaton** [comment]
> can you explain the which build and the error?

"yarn build:lib" command got failed while build the component. I have fixed this issue. Now we can able to execute the build command. Pls build and publish the npm package for testing (version : 9.0.0-alpha.2)

**Comment by JeffGreiner-eaton** [comment]
> > can you explain the which build and the error?
> 
> "yarn build:lib" command got failed while build the component. I have fixed this issue. Now we can able to execute the build command. Pls build and publish the npm package for testing (version : 9.0.0-alpha.2)

I'm in the dev branch and I don't a build error...
image

and this PR currently has a build problem

image

**Comment by RaghavendranC-Eaton** [comment]
> > > can you explain the which build and the error?
> > 
> > 
> > "yarn build:lib" command got failed while build the component. I have fixed this issue. Now we can able to execute the build command. Pls build and publish the npm package for testing (version : 9.0.0-alpha.2)
> 
> I'm in the dev branch and I don't see a build error... image
> 
> and this PR currently has a build problem
> 
> image

Kindly check the release/ng-15 branch for build issue.

**Comment by JeffGreiner-eaton** [comment]
Is there a reason why peerDependencies is missing in the dist package.json for this PR?
image

Pretty sure we should have peerDependencies
"@angular/cdk"
"@angular/core"
"@angular/material"

I need more information on why we are changing this

**Comment by RaghavendranC-Eaton** [comment]
> Is there a reason why peerDependencies is missing in the dist package.json for this PR? image
> 
> Pretty sure we should have peerDependencies "@angular/cdk" "@angular/core" "@angular/material"
> 
> I need more information on why we are changing this. ( I do see the build error is fixed for "No inputs were found in config file"

I'm not removed the peerDependencies values. while migrate to angular 15, its removed the values.   
In release/ng-15, you can see the build error. But I have fixed this issue in the "bug/build-issue" branch. Pls check that branch. Thanks

**Comment by RaghavendranC-Eaton** [comment]
@JeffGreiner-eaton I don't why circleci test got failed. In our application we used node version is 18.15.0
image
@daileytj Do you know why it gets failed.

**Comment by JeffGreiner-eaton** [comment]
> 

ok, for angular v15 you are saying we will not have peerDependencies on 
"@angular/cdk"
"@angular/core"
"@angular/material"

**Review by JeffGreiner-eaton — APPROVED** [review]

**Pull request merged**
